### ISSUE TITLE
[PS1] Namco Anthology 2 (Japan): Various issues

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#636]
In the new Namco Classic II, the screen right before you take your shot has severe visual issues; additionally, certain voice lines (like the "out of bounds" and "nice on" ones) sound too compressed.
Trying to boot the original Namco Classic II results in a black screen with some scratchy audio.
Both versions of Pac Attack suffer from https://github.com/ares-emulator/ares/issues/588.
In the new Valkryie, the text box background spills out the right side.
The old Valkryie crashes the entire emu, with:
```
Thread 43 "ares" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9d6d0700 (LWP 21035)]
0x0000555555c5a5f1 in ares::PlayStation::GPU::Render::pixel<128u> (
    this=this@entry=0x7fff9d6cfa90, point=..., point@entry=..., rgb=..., 
    uv=..., uv@entry=...) at ../ares/ps1/gpu/renderer.cpp:121
121	auto GPU::Render::pixel(Point point, Color rgb, Point uv) -> void {
(gdb) bt
#0  0x0000555555c5a5f1 in ares::PlayStation::GPU::Render::pixel<128u>(ares::PlayStation::GPU::Point, ares::PlayStation::GPU::Color, ares::PlayStation::GPU::Point) (this=this@entry=0x7fff9d6cfa90, point=..., 
    point@entry=..., rgb=..., uv=..., uv@entry=...)
    at ../ares/ps1/gpu/renderer.cpp:121
#1  0x0000555555c5aa59 in ares::PlayStation::GPU::Render::triangle<128u>()
    (this=this@entry=0x7fff9d6cfa90) at ../ares/ps1/gpu/renderer.cpp:272
#2  0x0000555555c5aba3 in ares::PlayStation::GPU::Render::quadrilateral<128u>()
    (this=0x7fff9d6cfa90) at ../ares/ps1/gpu/renderer.cpp:292
#3  0x0000555555c5acd0 in ares::PlayStation::GPU::Render::rectangle<0u>()
    (this=<optimized out>) at ../ares/ps1/gpu/gpu.hpp:245
#4  0x0000555555c4df3c in ares::PlayStation::GPU::Render::execute()
    (this=this@entry=0x7fff9d6cfa90) at ../ares/ps1/gpu/renderer.cpp:404
#5  0x0000555555c4e027 in ares::PlayStation::GPU::Renderer::main(unsigned long)
    (this=0x555570d4fab0 <ares::PlayStation::gpu+264560>)
    at ../ares/ps1/gpu/renderer.cpp:427
#6  0x0000555555c4ea44 in nall::function<void (unsigned long)>::member<ares::PlayStation::GPU::Renderer>::operator()(unsigned long) const
    (this=<optimized out>, p#0=<optimized out>) at ../nall/function.hpp:65
#7  0x00005555559211d3 in nall::function<void (unsigned long)>::operator()(unsigned long) const (p#0=<optimized out>, this=0x5555749c6be0)
    at ../nall/function.hpp:29
#8  nall::_threadCallback(void*) (parameter=0x5555749c6be0)
    at ../nall/thread.hpp:51
#9  0x00007ffff6a23609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#10 0x00007ffff6946133 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
Ares v128 nightly, built on July 12 2022
Linux Mint 20.2

**Comment by HeroponRikiBestest** [comment]
The crashing issue is no longer gone. Old Valkryie now has issues similar to the other NES games.

**Comment by HeroponRikiBestest** [comment]
https://github.com/ares-emulator/ares/commit/5283135a49e4017e99b93cae5f94ed8639653d88 fixed the input issues with pac attack. However, now that I can play them, both versions suffer from an issue where the music restarts every time you pause and unpause.
